package entities;
// Generated Apr 30, 2019 9:34:11 AM by Hibernate Tools 4.3.1



/**
 * Doibong generated by hbm2java
 */
public class Doibong  implements java.io.Serializable {


     private int maDoiBong;
     private String tenDoiBong;
     private String hinhAnh;
     private String huanLuanVien;
     private String ngaySinh;

    public Doibong() {
    }

    public Doibong(int maDoiBong, String tenDoiBong, String hinhAnh, String huanLuanVien, String ngaySinh) {
       this.maDoiBong = maDoiBong;
       this.tenDoiBong = tenDoiBong;
       this.hinhAnh = hinhAnh;
       this.huanLuanVien = huanLuanVien;
       this.ngaySinh = ngaySinh;
    }
   
    public int getMaDoiBong() {
        return this.maDoiBong;
    }
    
    public void setMaDoiBong(int maDoiBong) {
        this.maDoiBong = maDoiBong;
    }
    public String getTenDoiBong() {
        return this.tenDoiBong;
    }
    
    public void setTenDoiBong(String tenDoiBong) {
        this.tenDoiBong = tenDoiBong;
    }
    public String getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(String hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public String getHuanLuanVien() {
        return this.huanLuanVien;
    }
    
    public void setHuanLuanVien(String huanLuanVien) {
        this.huanLuanVien = huanLuanVien;
    }
    public String getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(String ngaySinh) {
        this.ngaySinh = ngaySinh;
    }




}


