package entities;
// Generated May 2, 2019 7:38:22 AM by Hibernate Tools 4.3.1



/**
 * Giaidau generated by hbm2java
 */
public class Giaidau  implements java.io.Serializable {


     private int maGiai;
     private String tenGiai;
     private String thoiGian;

    public Giaidau() {
    }

    public Giaidau(int maGiai, String tenGiai, String thoiGian) {
       this.maGiai = maGiai;
       this.tenGiai = tenGiai;
       this.thoiGian = thoiGian;
    }
   
    public int getMaGiai() {
        return this.maGiai;
    }
    
    public void setMaGiai(int maGiai) {
        this.maGiai = maGiai;
    }
    public String getTenGiai() {
        return this.tenGiai;
    }
    
    public void setTenGiai(String tenGiai) {
        this.tenGiai = tenGiai;
    }
    public String getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(String thoiGian) {
        this.thoiGian = thoiGian;
    }




}


