package entities;
// Generated May 28, 2019 9:59:44 PM by Hibernate Tools 4.3.1



/**
 * Giaidau generated by hbm2java
 */
public class Giaidau  implements java.io.Serializable {


     private Integer maGiai;
     private String tenGiai;
     private String thoiGian;

    public Giaidau() {
    }

    public Giaidau(String tenGiai, String thoiGian) {
       this.tenGiai = tenGiai;
       this.thoiGian = thoiGian;
    }
   
    public Integer getMaGiai() {
        return this.maGiai;
    }
    
    public void setMaGiai(Integer maGiai) {
        this.maGiai = maGiai;
    }
    public String getTenGiai() {
        return this.tenGiai;
    }
    
    public void setTenGiai(String tenGiai) {
        this.tenGiai = tenGiai;
    }
    public String getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(String thoiGian) {
        this.thoiGian = thoiGian;
    }




}


