package entities;
// Generated May 2, 2019 7:38:22 AM by Hibernate Tools 4.3.1



/**
 * Loaibanthang generated by hbm2java
 */
public class Loaibanthang  implements java.io.Serializable {


     private int maLoai;
     private String tenloai;

    public Loaibanthang() {
    }

    public Loaibanthang(int maLoai, String tenloai) {
       this.maLoai = maLoai;
       this.tenloai = tenloai;
    }
   
    public int getMaLoai() {
        return this.maLoai;
    }
    
    public void setMaLoai(int maLoai) {
        this.maLoai = maLoai;
    }
    public String getTenloai() {
        return this.tenloai;
    }
    
    public void setTenloai(String tenloai) {
        this.tenloai = tenloai;
    }




}


