package entities;
// Generated May 28, 2019 9:59:44 PM by Hibernate Tools 4.3.1



/**
 * Nhataitro generated by hbm2java
 */
public class Nhataitro  implements java.io.Serializable {


     private Integer maNhaTaiTro;
     private String tenNhaTaiTro;
     private String hinhThuc;

    public Nhataitro() {
    }

    public Nhataitro(String tenNhaTaiTro, String hinhThuc) {
       this.tenNhaTaiTro = tenNhaTaiTro;
       this.hinhThuc = hinhThuc;
    }
   
    public Integer getMaNhaTaiTro() {
        return this.maNhaTaiTro;
    }
    
    public void setMaNhaTaiTro(Integer maNhaTaiTro) {
        this.maNhaTaiTro = maNhaTaiTro;
    }
    public String getTenNhaTaiTro() {
        return this.tenNhaTaiTro;
    }
    
    public void setTenNhaTaiTro(String tenNhaTaiTro) {
        this.tenNhaTaiTro = tenNhaTaiTro;
    }
    public String getHinhThuc() {
        return this.hinhThuc;
    }
    
    public void setHinhThuc(String hinhThuc) {
        this.hinhThuc = hinhThuc;
    }




}


