package entities;
// Generated Jun 17, 2019 11:57:59 PM by Hibernate Tools 4.3.1



/**
 * Qd generated by hbm2java
 */
public class Qd  implements java.io.Serializable {


     private Integer maQuyDinh;
     private String tenLuat;
     private Integer numberMax;
     private Integer numberMin;
     private Integer thang;
     private Integer hoa;
     private Integer thua;
     private Integer uutienxephang;

    public Qd() {
    }

	
    public Qd(String tenLuat) {
        this.tenLuat = tenLuat;
    }
    public Qd(String tenLuat, Integer numberMax, Integer numberMin, Integer thang, Integer hoa, Integer thua, Integer uutienxephang) {
       this.tenLuat = tenLuat;
       this.numberMax = numberMax;
       this.numberMin = numberMin;
       this.thang = thang;
       this.hoa = hoa;
       this.thua = thua;
       this.uutienxephang = uutienxephang;
    }
   
    public Integer getMaQuyDinh() {
        return this.maQuyDinh;
    }
    
    public void setMaQuyDinh(Integer maQuyDinh) {
        this.maQuyDinh = maQuyDinh;
    }
    public String getTenLuat() {
        return this.tenLuat;
    }
    
    public void setTenLuat(String tenLuat) {
        this.tenLuat = tenLuat;
    }
    public Integer getNumberMax() {
        return this.numberMax;
    }
    
    public void setNumberMax(Integer numberMax) {
        this.numberMax = numberMax;
    }
    public Integer getNumberMin() {
        return this.numberMin;
    }
    
    public void setNumberMin(Integer numberMin) {
        this.numberMin = numberMin;
    }
    public Integer getThang() {
        return this.thang;
    }
    
    public void setThang(Integer thang) {
        this.thang = thang;
    }
    public Integer getHoa() {
        return this.hoa;
    }
    
    public void setHoa(Integer hoa) {
        this.hoa = hoa;
    }
    public Integer getThua() {
        return this.thua;
    }
    
    public void setThua(Integer thua) {
        this.thua = thua;
    }
    public Integer getUutienxephang() {
        return this.uutienxephang;
    }
    
    public void setUutienxephang(Integer uutienxephang) {
        this.uutienxephang = uutienxephang;
    }




}


