package entities;
// Generated Jun 17, 2019 10:57:10 PM by Hibernate Tools 4.3.1



/**
 * Santhidau generated by hbm2java
 */
public class Santhidau  implements java.io.Serializable {


     private Integer id;
     private String tenSan;

    public Santhidau() {
    }

    public Santhidau(String tenSan) {
       this.tenSan = tenSan;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTenSan() {
        return this.tenSan;
    }
    
    public void setTenSan(String tenSan) {
        this.tenSan = tenSan;
    }




}


