package entities;
// Generated May 2, 2019 7:38:22 AM by Hibernate Tools 4.3.1



/**
 * Trandau generated by hbm2java
 */
public class Trandau  implements java.io.Serializable {


     private int maTran;
     private int maGiai;
     private String thoiGian;
     private int vong;
     private int chuNha;
     private int tySo;
     private int khach;
     private int san;
     private String maTrongTai;

    public Trandau() {
    }

    public Trandau(int maTran, int maGiai, String thoiGian, int vong, int chuNha, int tySo, int khach, int san, String maTrongTai) {
       this.maTran = maTran;
       this.maGiai = maGiai;
       this.thoiGian = thoiGian;
       this.vong = vong;
       this.chuNha = chuNha;
       this.tySo = tySo;
       this.khach = khach;
       this.san = san;
       this.maTrongTai = maTrongTai;
    }
   
    public int getMaTran() {
        return this.maTran;
    }
    
    public void setMaTran(int maTran) {
        this.maTran = maTran;
    }
    public int getMaGiai() {
        return this.maGiai;
    }
    
    public void setMaGiai(int maGiai) {
        this.maGiai = maGiai;
    }
    public String getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(String thoiGian) {
        this.thoiGian = thoiGian;
    }
    public int getVong() {
        return this.vong;
    }
    
    public void setVong(int vong) {
        this.vong = vong;
    }
    public int getChuNha() {
        return this.chuNha;
    }
    
    public void setChuNha(int chuNha) {
        this.chuNha = chuNha;
    }
    public int getTySo() {
        return this.tySo;
    }
    
    public void setTySo(int tySo) {
        this.tySo = tySo;
    }
    public int getKhach() {
        return this.khach;
    }
    
    public void setKhach(int khach) {
        this.khach = khach;
    }
    public int getSan() {
        return this.san;
    }
    
    public void setSan(int san) {
        this.san = san;
    }
    public String getMaTrongTai() {
        return this.maTrongTai;
    }
    
    public void setMaTrongTai(String maTrongTai) {
        this.maTrongTai = maTrongTai;
    }




}


