package entities;
// Generated Jun 17, 2019 11:57:59 PM by Hibernate Tools 4.3.1



/**
 * Xemhang generated by hbm2java
 */
public class Xemhang  implements java.io.Serializable {


     private Integer maDoiBong;
     private int tranThang;
     private int tranHoa;
     private int tranBai;
     private int banThang;
     private int banBai;
     private int hieuSo;
     private int diem;

    public Xemhang() {
    }

    public Xemhang(int tranThang, int tranHoa, int tranBai, int banThang, int banBai, int hieuSo, int diem) {
       this.tranThang = tranThang;
       this.tranHoa = tranHoa;
       this.tranBai = tranBai;
       this.banThang = banThang;
       this.banBai = banBai;
       this.hieuSo = hieuSo;
       this.diem = diem;
    }
   
    public Integer getMaDoiBong() {
        return this.maDoiBong;
    }
    
    public void setMaDoiBong(Integer maDoiBong) {
        this.maDoiBong = maDoiBong;
    }
    public int getTranThang() {
        return this.tranThang;
    }
    
    public void setTranThang(int tranThang) {
        this.tranThang = tranThang;
    }
    public int getTranHoa() {
        return this.tranHoa;
    }
    
    public void setTranHoa(int tranHoa) {
        this.tranHoa = tranHoa;
    }
    public int getTranBai() {
        return this.tranBai;
    }
    
    public void setTranBai(int tranBai) {
        this.tranBai = tranBai;
    }
    public int getBanThang() {
        return this.banThang;
    }
    
    public void setBanThang(int banThang) {
        this.banThang = banThang;
    }
    public int getBanBai() {
        return this.banBai;
    }
    
    public void setBanBai(int banBai) {
        this.banBai = banBai;
    }
    public int getHieuSo() {
        return this.hieuSo;
    }
    
    public void setHieuSo(int hieuSo) {
        this.hieuSo = hieuSo;
    }
    public int getDiem() {
        return this.diem;
    }
    
    public void setDiem(int diem) {
        this.diem = diem;
    }




}


