
package bongda1.pkg0;

import dao.CauThuDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import entities.*;
import dao.*;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
public class DoiBongWindow extends javax.swing.JPanel {
    String imgPath=null;
    //String dd="C:\\Users\\Admin\\Desktop\\anh\\hinh 3.jpg";
    //Resize image
    public ImageIcon ResizeImage(String imagePath,byte[] pic)
    {
        ImageIcon myImage=null;
        if(imagePath!=null)
        {
            myImage=new ImageIcon(imagePath);
                }
        else
        {
            myImage =new ImageIcon(pic);
        }
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lb_img.getWidth(), lb_img.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    }
    public DoiBongWindow() {
        initComponents();
        LoadData();
        LoadCB();
        //lb_imgimg.setIcon(new ImageIcon("C:\\Users\\Admin\\Desktop\\anh\\hinh 3.jpg"));
    }    
    CauThuDAO ctd=new CauThuDAO();
    DoiBongDao dbDao=new DoiBongDao();
    
    public int maCauThu;
    public String tenCauThu;
    public int Vitri;
    public int soAo;
    public String NgaySinh;
    public int BanThang;
    public int TheVang;
    public int TheDo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void LoadData()
    {
        DefaultTableModel dtm=new DefaultTableModel();
        dtm.addColumn("MaCauThu");
        dtm.addColumn("TenCauThu");
        dtm.addColumn("ViTri");
        dtm.addColumn("SoAo");
        dtm.addColumn("NgaySinh");
        dtm.addColumn("BanThang");
        dtm.addColumn("TheVang");
        dtm.addColumn("TheDO");
        dtm.addColumn("MaDoiBong");
        for(entities.Cauthu ct : this.ctd.load_danhSach())
        {
            dtm.addRow(new Object[]{ct.getMaCauThu(),ct.getTenCauThu(),ct.getViTri(),ct.getNgaySinh(),ct.getBanThang(),ct.getTheVang(),ct.getTheDo(),ct.getMaDoiBong()});
            
        }
        this.tbcauthu.setModel(dtm);
        this.tbcauthu.repaint();
        this.tbcauthu.revalidate();
    }
    private void LoadDataDK(int maDoiBong)
    {
        DefaultTableModel dtm=new DefaultTableModel();
        dtm.addColumn("MaCauThu");
        dtm.addColumn("TenCauThu");
        dtm.addColumn("ViTri");
        dtm.addColumn("SoAo");
        dtm.addColumn("NgaySinh");
        dtm.addColumn("BanThang");
        dtm.addColumn("TheVang");
        dtm.addColumn("TheDO");
        dtm.addColumn("MaDoiBong");
        for(entities.Cauthu ct : this.ctd.load_danhSachDK_db(maDoiBong))
        {
            dtm.addRow(new Object[]{ct.getMaCauThu(),ct.getTenCauThu(),ct.getViTri(),ct.getNgaySinh(),ct.getBanThang(),ct.getTheVang(),ct.getTheDo(),ct.getMaDoiBong()});
            
        }
        this.tbcauthu.setModel(dtm);
        this.tbcauthu.repaint();
        this.tbcauthu.revalidate();
    }
    public void LoadCB()
    {
        DefaultComboBoxModel model=new DefaultComboBoxModel();
        model.addElement(new Doibong(0,"--Chon doi bong-"));
        for(entities.Doibong db : this.dbDao.load_danhSach())
        {
            
            model.addElement(new Doibong(db.getMaDoiBong(),db.getTenDoiBong()));
            //cb_doiBong.addItem(db.getTenDoiBong());
        }       

        cb_doiBong.setModel(model);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcauthu = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_XoaDB = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lb_img = new javax.swing.JLabel();
        btn_CapNhap = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_doiBong = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_HLV = new javax.swing.JTextField();
        txt_NS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_SanNha = new javax.swing.JTextField();
        btn_ThemDB = new javax.swing.JButton();
        btn_xoaDB = new javax.swing.JButton();
        txt_TenCauThu = new javax.swing.JTextField();
        btn_TimKiem = new javax.swing.JButton();
        txtimg = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jButton5.setText("jButton5");

        jLabel2.setText("jLabel2");

        tbcauthu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbcauthu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcauthuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcauthu);

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_XoaDB.setText("Cập Nhập");
        btn_XoaDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaDBActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lb_img.setText("Hình Ảnh");

        btn_CapNhap.setText("Cập Nhập ");
        btn_CapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhapActionPerformed(evt);
            }
        });

        jLabel3.setText("Huấn Luận Viên");

        jLabel4.setText("Danh Sách Cầu Thủ");

        jLabel5.setText("Đội Bóng");

        cb_doiBong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_doiBongItemStateChanged(evt);
            }
        });
        cb_doiBong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cb_doiBongMouseMoved(evt);
            }
        });
        cb_doiBong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_doiBongMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb_doiBongMousePressed(evt);
            }
        });
        cb_doiBong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_doiBongActionPerformed(evt);
            }
        });
        cb_doiBong.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb_doiBongPropertyChange(evt);
            }
        });

        jLabel6.setText("Ngày Sinh");

        txt_HLV.setText("txtHLV");

        txt_NS.setText("txtNS");

        jLabel1.setText("Sân Nhà ");

        btn_ThemDB.setText("Thêm");
        btn_ThemDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemDBActionPerformed(evt);
            }
        });

        btn_xoaDB.setText("Xóa");
        btn_xoaDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaDBActionPerformed(evt);
            }
        });

        txt_TenCauThu.setText("Nhập Tên Cầu Thủ");
        txt_TenCauThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_TenCauThuMouseClicked(evt);
            }
        });
        txt_TenCauThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenCauThuActionPerformed(evt);
            }
        });

        btn_TimKiem.setText("Tìm Kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        txtimg.setText("jTextField1");

        jButton2.setText("Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5)
                                .addGap(188, 188, 188)
                                .addComponent(cb_doiBong, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(btn_CapNhap)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_NS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_HLV, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_SanNha, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(btn_ThemDB)
                                        .addGap(59, 59, 59)
                                        .addComponent(btn_xoaDB)
                                        .addGap(35, 35, 35)
                                        .addComponent(jButton2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lb_img, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(85, 85, 85)
                                .addComponent(btn_XoaDB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)
                                .addComponent(btnXoa)
                                .addGap(317, 317, 317))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(txt_TenCauThu, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_doiBong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TenCauThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_TimKiem))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(jButton1)
                            .addComponent(btn_XoaDB)
                            .addComponent(btn_xoaDB)
                            .addComponent(btn_ThemDB)
                            .addComponent(btn_CapNhap)
                            .addComponent(jButton2))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_img, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_HLV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_NS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_SanNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int cf=JOptionPane.showConfirmDialog(null,"Co chac xoa ko","xac nhan",JOptionPane.YES_NO_OPTION);
        if(cf==JOptionPane.YES_OPTION)
        {
            
         int name= Integer.parseInt(this.tbcauthu.getValueAt(this.tbcauthu.getSelectedRow(), 0).toString());
              entities.Cauthu ct=ctd.load(name);
           
            if(this.ctd.delete(ct))
            {
               JOptionPane.showMessageDialog(null," xoa thanh cong");
                LoadData();
            } else {
                JOptionPane.showMessageDialog(null," xoa khong thanh cong");
                
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btn_XoaDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaDBActionPerformed
       
        SuaCauThu sct=new SuaCauThu(maCauThu);
        sct.setVisible(true);
    }//GEN-LAST:event_btn_XoaDBActionPerformed

    private void tbcauthuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcauthuMouseClicked
        maCauThu = Integer.parseInt(this.tbcauthu.getValueAt(this.tbcauthu.getSelectedRow(), 0).toString());
        tenCauThu= this.tbcauthu.getValueAt(this.tbcauthu.getSelectedRow(), 1).toString();
        Vitri = Integer.parseInt(this.tbcauthu.getValueAt(this.tbcauthu.getSelectedRow(), 2).toString());
        soAo =Integer.parseInt(this.tbcauthu.getValueAt(this.tbcauthu.getSelectedRow(), 3).toString());  
        NgaySinh= this.tbcauthu.getValueAt(this.tbcauthu.getSelectedRow(), 4).toString();
        BanThang =Integer.parseInt(this.tbcauthu.getValueAt(this.tbcauthu.getSelectedRow(), 5).toString());  
        TheVang =Integer.parseInt(this.tbcauthu.getValueAt(this.tbcauthu.getSelectedRow(), 6).toString());  
        TheDo =Integer.parseInt(this.tbcauthu.getValueAt(this.tbcauthu.getSelectedRow(),7).toString()); 
    }//GEN-LAST:event_tbcauthuMouseClicked

    private void cb_doiBongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_doiBongMouseClicked
     // JOptionPane.showMessageDialog(cb_doiBong,cb_doiBong.getSelectedItem()+"con ga con");
    }//GEN-LAST:event_cb_doiBongMouseClicked

    private void cb_doiBongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_doiBongActionPerformed
      int ma=((Doibong)cb_doiBong.getSelectedItem()).getMaDoiBong();
        LoadDataDK(ma);
    }//GEN-LAST:event_cb_doiBongActionPerformed

    private void cb_doiBongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_doiBongMousePressed
        //JOptionPane.showMessageDialog(cb_doiBong,cb_doiBong.getSelectedItem()+"con ga con");
    }//GEN-LAST:event_cb_doiBongMousePressed

    private void cb_doiBongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_doiBongMouseMoved
       
    }//GEN-LAST:event_cb_doiBongMouseMoved

    private void cb_doiBongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_doiBongItemStateChanged
        int ma=((Doibong)cb_doiBong.getSelectedItem()).getMaDoiBong();
        LoadDataDK(ma);
        //JOptionPane.showMessageDialog(this, ma);
        Doibong db=new Doibong();
        db=dbDao.load(ma);
        if(db!=null){
            txt_SanNha.setText(db.getSanNha());
            txt_HLV.setText(db.getHuanLuanVien());
            txt_NS.setText(db.getNgaySinh());
            String chuoi=db.getHinhAnh();
            txtimg.setText(chuoi);
            lb_img.setIcon(new ImageIcon(chuoi));
       }
    }//GEN-LAST:event_cb_doiBongItemStateChanged

    private void cb_doiBongPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb_doiBongPropertyChange
    
    }//GEN-LAST:event_cb_doiBongPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ThemCauThu ct=new ThemCauThu();
        ct.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_ThemDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemDBActionPerformed
        ThemDoiBong db=new ThemDoiBong();
        db.setVisible(true);
    }//GEN-LAST:event_btn_ThemDBActionPerformed

    private void btn_xoaDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaDBActionPerformed
       
        int cf=JOptionPane.showConfirmDialog(null,"co chac xoa doi bong ko","xac nhan",JOptionPane.YES_NO_OPTION);
        if(cf==JOptionPane.YES_OPTION)
        {
            int ma=((Doibong)cb_doiBong.getSelectedItem()).getMaDoiBong();
           
          Doibong db=dbDao.load(ma);
           
            if(this.dbDao.delete(db))
            {
                JOptionPane.showMessageDialog(null," xoa thanh cong");
                LoadData();
            } else {
                JOptionPane.showMessageDialog( null,"xoa khong thanh cong");
            }
        }
    }//GEN-LAST:event_btn_xoaDBActionPerformed

    private void btn_CapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhapActionPerformed
         int ma=((Doibong)cb_doiBong.getSelectedItem()).getMaDoiBong();
         String ten=cb_doiBong.getSelectedItem().toString();
         String ha="";
         String hlv=txt_HLV.getText();
         String ns=txt_NS.getText();
         String sn=txt_SanNha.getText();
        SuaDoiBong sdb=new SuaDoiBong(ma,ten,ha,hlv,sn,ns);
        sdb.setVisible(true);
    }//GEN-LAST:event_btn_CapNhapActionPerformed

    private void LoadDataTimKiem(String tenCauThu)
    {
        DefaultTableModel dtm=new DefaultTableModel();
        dtm.addColumn("MaCauThu");
        dtm.addColumn("TenCauThu");
        dtm.addColumn("ViTri");
        dtm.addColumn("SoAo");
        dtm.addColumn("NgaySinh");
        dtm.addColumn("BanThang");
        dtm.addColumn("TheVang");
        dtm.addColumn("TheDO");
        dtm.addColumn("MaDoiBong");
        for(entities.Cauthu ct : this.ctd.load_danhSach_TimKiem(tenCauThu))
        {
            dtm.addRow(new Object[]{ct.getMaCauThu(),ct.getTenCauThu(),ct.getViTri(),ct.getNgaySinh(),ct.getBanThang(),ct.getTheVang(),ct.getTheDo(),ct.getMaDoiBong()});
            
        }
        this.tbcauthu.setModel(dtm);
        this.tbcauthu.repaint();
        this.tbcauthu.revalidate();
    }
    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        String ten=txt_TenCauThu.getText();
        LoadDataTimKiem(ten);
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void txt_TenCauThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TenCauThuMouseClicked
        txt_TenCauThu.setText("");
    }//GEN-LAST:event_txt_TenCauThuMouseClicked

    private void txt_TenCauThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenCauThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenCauThuActionPerformed
    JasperDesign jd;
    JasperReport jr;
    JasperPrint jp;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Connection con =null;
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost/dbbongdanew","root","");
            //JOptionPane.showMessageDialog(null,"ket noi thanh cong");
            File f=new File("src/report1.jrxml");
            if(f.exists())
            {
                JOptionPane.showMessageDialog(null,"ton tai");
            }
            
            jd =JRXmlLoader.load(f);
            jr=JasperCompileManager.compileReport(jd);
            jp=JasperFillManager.fillReport(jr,null,con);
            JasperViewer.viewReport(jp,false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"khong noi thanh cong");
           
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btn_CapNhap;
    private javax.swing.JButton btn_ThemDB;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_XoaDB;
    private javax.swing.JButton btn_xoaDB;
    private javax.swing.JComboBox<String> cb_doiBong;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_img;
    private javax.swing.JTable tbcauthu;
    private javax.swing.JTextField txt_HLV;
    private javax.swing.JTextField txt_NS;
    private javax.swing.JTextField txt_SanNha;
    private javax.swing.JTextField txt_TenCauThu;
    private javax.swing.JTextField txtimg;
    // End of variables declaration//GEN-END:variables
}
