package bongda1.pkg0;

import javax.swing.JOptionPane;
import dao.*;
import entities.*;
import org.hibernate.*;
        

/**
 *
 * @author Admin
 */
public class SuaLichThiDau extends javax.swing.JFrame {

    /**
     * Creates new form SuaLichThiDau
     */
    int maTran;
    LichThiDauDAO ltdDAO=new  LichThiDauDAO();
    public SuaLichThiDau() {
        initComponents();
    }
    public SuaLichThiDau(int maTran1) {
        initComponents();
        maTran=maTran1;
        JOptionPane.showMessageDialog(this, "kq"+maTran);
        load1Tran(maTran);
    }
    public void load1Tran(int maTran)
    {
        Trandau td=ltdDAO.load(maTran);
        if(td!=null){
            txt_MT.setText(td.getMaTran().toString());
            txt_GD.setText(String.valueOf(td.getMaGiai()));
            txt_NG.setText(td.getThoiGian());
            txt_VD.setText(String.valueOf(td.getVong()));
            txt_MDN.setText(String.valueOf(td.getMaChuNha()));
            txt_tenDN.setText(td.getTenChuNha());
            txt_btN.setText(td.getTschuNha());
            txt_btK.setText(String.valueOf(td.getTskhach()));
            txt_maDK.setText(String.valueOf(td.getMaKhach()));
            txt_tenDK.setText(td.getTenDoiKhach());
            txt_san.setText(String.valueOf(td.getSan()));
            txt_maTT.setText(String.valueOf(td.getMaTrongTai()));
        }
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_maDK = new javax.swing.JTextField();
        txt_tenDK = new javax.swing.JTextField();
        txt_btK = new javax.swing.JTextField();
        txt_san = new javax.swing.JTextField();
        txt_maTT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_GD = new javax.swing.JTextField();
        txt_NG = new javax.swing.JTextField();
        txt_VD = new javax.swing.JTextField();
        txt_MDN = new javax.swing.JTextField();
        lbBig = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddTD = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_tenDN = new javax.swing.JTextField();
        txt_btN = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_MT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Trọng Tài");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Đội Nhà");

        jLabel9.setText("Tên Đội Khách");

        jLabel10.setText("BT Khách");

        jLabel11.setText("BT Nhà");

        lbBig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBig.setText("SỬA LỊCH THI ĐẤU");

        jLabel2.setText("Tên Dội Nhà");

        jLabel3.setText("Mã Đội Khách");

        jLabel4.setText("Ngày-Giờ");

        jLabel5.setText("Sân");

        btnAddTD.setText("Save");
        btnAddTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTDActionPerformed(evt);
            }
        });

        jLabel6.setText("Vòng đấu");

        jLabel7.setText("Giải Đấu");

        jLabel12.setText("Mã Trận ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBig, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_GD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_VD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(txt_MDN, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txt_NG, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_btN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_tenDK, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(txt_san)
                        .addComponent(txt_maDK, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_maTT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_btK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_MT, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(197, 197, 197))
            .addGroup(layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(btnAddTD)
                .addGap(107, 107, 107)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbBig, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(txt_GD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txt_NG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(txt_VD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_btK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txt_MDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_san, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(txt_tenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_btN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_MT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTD)
                    .addComponent(jButton1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTDActionPerformed

        Trandau td=new Trandau();
        td.setMaGiai(Integer.parseInt(this.txt_GD.getText()));
        td.setThoiGian(this.txt_NG.getText());
        td.setVong(Integer.parseInt(this.txt_VD.getText()));
        td.setMaChuNha(Integer.parseInt(this.txt_MDN.getText()));
        td.setTenChuNha(this.txt_tenDN.getText());
        td.setTschuNha(this.txt_btN.getText());
        td.setTskhach(Integer.parseInt(this.txt_btK.getText()));
        td.setMaKhach(Integer.parseInt(this.txt_btK.getText()));
        td.setTenDoiKhach(this.txt_tenDK.getText());
        td.setSan(Integer.parseInt(this.txt_san.getText()));
        td.setMaTrongTai(Integer.parseInt(this.txt_maTT.getText()));
        td.setMaTran(Integer.parseInt(txt_MT.getText()));
        if(ltdDAO.update(td))
        {
            JOptionPane.showMessageDialog(rootPane,"Cap Nhap thanh cong");

        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"That bai");
        }
        //        if(checkinfomation())
        //       {
            //            Calendar cal = Calendar.getInstance();
            //            Date date = JDDate.getDate();//cal.getTime();
            //            SimpleDateFormat fr=new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            //            String NgayGio = fr.format(date).toString();
            //            int San =GetIDCombodoiSanDau(cboSan.getSelectedItem().toString());
            //            int Doi1 =GetIDCombodoiBong(cboDoi1.getSelectedItem().toString());
            //            int Doi2 =GetIDCombodoiBong(CboDoi2.getSelectedItem().toString());
            //            int Giai =GetIDComboGiaiDau(cboGiaiDau.getSelectedItem().toString());
            //            int Vong =GetIDComboVongdau(cboVongDau.getSelectedItem().toString());
            //            String TT =GetIDTT(cboTT.getSelectedItem().toString());
            //            if(Doi1 == -1 || Doi2 == -1){
                //                JOptionPane.showMessageDialog(rootPane,"Gặp lỗi lấy thông tin đội bóng");
                //                return;
                //            }
            //            TranDauDAO tdd=new TranDauDAO();
            //            Trandau  tt=new Trandau();
            //            tt.setChuNha(Doi1);
            //            tt.setKhach(Doi2);
            //            tt.setMaGiai(Giai);
            //            tt.setMaTrongTai(TT);
            //            tt.setSan(San);
            //            tt.setTySo(-1);
            //            tt.setVong(Vong);
            //            tt.setThoiGian(NgayGio);
            //             if(lc.equals("Update")){tt.setMaTran(Integer.parseInt(mMaTran));}
            //            if( lc.equals("Insert")?tdd.AddTranDau(tt):tdd.UpdateTranDau(tt))
            //            {
                //                JOptionPane.showMessageDialog(rootPane,"Thao tác thành công");
                //                mContaxt.addSuccessful1();
                //            }
            //            else
            //            {
                //                JOptionPane.showMessageDialog(rootPane,"Thao tác thất bại");
                //            }
            //           }
        //           else{
            //               //JOptionPane.showMessageDialog(rootPane,"UserName da ton tai. Vui long thu mot username khac");
            //            }
    }//GEN-LAST:event_btnAddTDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws java.lang.InstantiationException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaLichThiDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaLichThiDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaLichThiDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaLichThiDau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTD;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbBig;
    private javax.swing.JTextField txt_GD;
    private javax.swing.JTextField txt_MDN;
    private javax.swing.JTextField txt_MT;
    private javax.swing.JTextField txt_NG;
    private javax.swing.JTextField txt_VD;
    private javax.swing.JTextField txt_btK;
    private javax.swing.JTextField txt_btN;
    private javax.swing.JTextField txt_maDK;
    private javax.swing.JTextField txt_maTT;
    private javax.swing.JTextField txt_san;
    private javax.swing.JTextField txt_tenDK;
    private javax.swing.JTextField txt_tenDN;
    // End of variables declaration//GEN-END:variables
}
